export function buildTextReport(result) {
  const lines = [];

  lines.push("PROJECTPULSE AI");
  lines.push("Project Communication Intelligence Report");
  lines.push("=".repeat(55));
  lines.push("");

  lines.push(`Conversation ID: ${result.conversation_id}`);
  lines.push(`Source: ${result.source}`);
  lines.push("");

  lines.push("SUMMARY");
  lines.push("-".repeat(55));
  lines.push(result.summary);
  lines.push("");

  lines.push("ACTION ITEMS");
  lines.push("-".repeat(55));

  if (result.tasks.length === 0) {
    lines.push("No action items detected.");
  } else {
    result.tasks.forEach((task, index) => {
      lines.push(`${index + 1}. ${task.task}`);
      lines.push(`   Responsible: ${task.responsible}`);
      lines.push(`   Deadline: ${task.deadline || "Not detected"}`);
      lines.push(`   Status: ${task.status}`);
      lines.push("");
    });
  }

  lines.push("");
  lines.push("DECISIONS");
  lines.push("-".repeat(55));

  if (result.decisions.length === 0) {
    lines.push("No confirmed decisions detected.");
  } else {
    result.decisions.forEach((decision, index) => {
      lines.push(`${index + 1}. ${decision.decision}`);
      lines.push(`   Status: ${decision.status}`);
      lines.push("");
    });
  }

  lines.push("");
  lines.push("PENDING APPROVALS");
  lines.push("-".repeat(55));

  if (result.approvals.length === 0) {
    lines.push("No pending approvals detected.");
  } else {
    result.approvals.forEach((approval, index) => {
      lines.push(`${index + 1}. ${approval.item}`);
      lines.push(`   Status: ${approval.status}`);
      lines.push("");
    });
  }

  lines.push("");
  lines.push("ATTENTION NEEDED");
  lines.push("-".repeat(55));

  if (result.attention_needed.length === 0) {
    lines.push("No urgent attention items detected.");
  } else {
    result.attention_needed.forEach((item, index) => {
      lines.push(`${index + 1}. ${item.message}`);
      lines.push(`   Type: ${item.type}`);
      lines.push(`   Detail: ${item.detail}`);
      lines.push("");
    });
  }

  lines.push("");
  lines.push("=".repeat(55));
  lines.push("Generated by ProjectPulse AI");
  lines.push("ArchScale Guild Hackathon · AS-02");

  return lines.join("\n");
}


export function downloadTextReport(result) {
  const report = buildTextReport(result);

  const blob = new Blob(
    [report],
    {
      type: "text/plain;charset=utf-8",
    }
  );

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");

  link.href = url;

  link.download =
    `projectpulse-conversation-${result.conversation_id}.txt`;

  document.body.appendChild(link);

  link.click();

  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}